services:
  nginx:
    build: ./test-nginx
    container_name: test-nginx
    ports:
      - 8080:80
    networks:
      - testnet

  crawler:
    image: webrecorder/browsertrix-crawler:1.7.1
    container_name: test-crawler
    networks:
      - testnet
    volumes:
      - ./crawls:/crawls:Z
    command:
      # https://crawler.docs.browsertrix.com/user-guide/cli-options/
      [
        "crawl",
        "--url", "http://nginx/",
        "--collection", "testcrawl",
        "--text",
        "--screenshot"
      ]

networks:
  testnet:
    driver: bridge
